# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.cache/wt [current_project]
set_property parent.project_path G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths g:/deverlopboard/a35t_code/miz_ip_lib/HDMI_FPGA_ML_A7 [current_project]
set_property ip_output_repo g:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/HDMI_tx.v
  G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/video_data_gen.v
}
read_ip -quiet G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/ip/HDMI_FPGA_ML_A7_0/HDMI_FPGA_ML_A7_0.xci

read_ip -quiet G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all g:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all g:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/HDMI_tx.xdc
set_property used_in_implementation false [get_files G:/deverlopboard/a35t_code/hdmi1_tx_35t_1080p60hz/08_hdmi_tx.srcs/HDMI_tx.xdc]


synth_design -top HDMI_tx_test -part xc7a35tftg256-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef HDMI_tx_test.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file HDMI_tx_test_utilization_synth.rpt -pb HDMI_tx_test_utilization_synth.pb"
