
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_N]
set_property IOSTANDARD LVCMOS33 [get_ports clk_27M]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_N]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_N]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_N]
set_property IOSTANDARD LVCMOS33 [get_ports KEY]
set_property PACKAGE_PIN F4 [get_ports HDMI_D2_P]
set_property PACKAGE_PIN F2 [get_ports HDMI_D1_P]

set_property PACKAGE_PIN P6 [get_ports {LED[3]}]
set_property PACKAGE_PIN L5 [get_ports {LED[2]}]
set_property PACKAGE_PIN N2 [get_ports {LED[1]}]
set_property PACKAGE_PIN N3 [get_ports {LED[0]}]
set_property PACKAGE_PIN K12 [get_ports KEY]
set_property PACKAGE_PIN F5 [get_ports HDMI_CLK_P]
set_property PACKAGE_PIN N11 [get_ports clk_27M]
set_property PACKAGE_PIN G5 [get_ports HDMI_D0_P]
