# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a75tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir K:/hdmi_tx_75t/08_hdmi_tx.cache/wt [current_project]
set_property parent.project_path K:/hdmi_tx_75t/08_hdmi_tx.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths k:/miz_ip_lib/HDMI_FPGA_ML_A7 [current_project]
set_property ip_output_repo k:/hdmi_tx_75t/08_hdmi_tx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet K:/hdmi_tx_75t/08_hdmi_tx.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files K:/hdmi_tx_75t/08_hdmi_tx.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet k:/hdmi_tx_75t/08_hdmi_tx.srcs/sources_1/ip/HDMI_FPGA_ML_A7_0/HDMI_FPGA_ML_A7_0.dcp
set_property used_in_implementation false [get_files k:/hdmi_tx_75t/08_hdmi_tx.srcs/sources_1/ip/HDMI_FPGA_ML_A7_0/HDMI_FPGA_ML_A7_0.dcp]
read_verilog -library xil_defaultlib {
  K:/hdmi_tx_75t/08_hdmi_tx.srcs/sources_1/HDMI_tx.v
  K:/hdmi_tx_75t/08_hdmi_tx.srcs/sources_1/video_data_gen.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc K:/hdmi_tx_75t/08_hdmi_tx.srcs/HDMI_tx.xdc
set_property used_in_implementation false [get_files K:/hdmi_tx_75t/08_hdmi_tx.srcs/HDMI_tx.xdc]


synth_design -top HDMI_tx_test -part xc7a75tfgg484-2


write_checkpoint -force -noxdef HDMI_tx_test.dcp

catch { report_utilization -file HDMI_tx_test_utilization_synth.rpt -pb HDMI_tx_test_utilization_synth.pb }
