# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/A7_Demo/S01_CH08_UART/UART/UART.cache/wt [current_project]
set_property parent.project_path F:/A7_Demo/S01_CH08_UART/UART/UART.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/A7_Demo/S01_CH08_UART/UART/UART.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/A7_Demo/S01_CH08_UART/UART/UART.srcs/sources_1/new/uart_tx_path.v
  F:/A7_Demo/S01_CH08_UART/UART/UART.srcs/sources_1/new/uart_rx_path.v
  F:/A7_Demo/S01_CH08_UART/UART/UART.srcs/sources_1/new/uart_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/A7_Demo/S01_CH08_UART/UART/UART.srcs/constrs_1/new/Artix_pin.xdc
set_property used_in_implementation false [get_files F:/A7_Demo/S01_CH08_UART/UART/UART.srcs/constrs_1/new/Artix_pin.xdc]


synth_design -top uart_top -part xc7a100tfgg484-2


write_checkpoint -force -noxdef uart_top.dcp

catch { report_utilization -file uart_top_utilization_synth.rpt -pb uart_top_utilization_synth.pb }
