
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports KEY]

set_property IOSTANDARD LVCMOS33 [get_ports dip[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dip[7]]

set_property PACKAGE_PIN L13 [get_ports i2c_clk]


set_property IOSTANDARD LVCMOS33 [get_ports clk_27m]
set_property IOSTANDARD LVCMOS33 [get_ports de_in]
set_property IOSTANDARD LVCMOS33 [get_ports hs_in]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_data]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_sck]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_sdin]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_ws]
set_property IOSTANDARD LVCMOS33 [get_ports it6802_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports vs_in]

set_property PACKAGE_PIN P16 [get_ports {b_in[7]}]
set_property PACKAGE_PIN N14 [get_ports {b_in[6]}]
set_property PACKAGE_PIN P14 [get_ports {b_in[5]}]
set_property PACKAGE_PIN M16 [get_ports {b_in[4]}]
set_property PACKAGE_PIN N16 [get_ports {b_in[3]}]
set_property PACKAGE_PIN L15 [get_ports {b_in[2]}]
set_property PACKAGE_PIN M15 [get_ports {b_in[1]}]
set_property PACKAGE_PIN L14 [get_ports {b_in[0]}]
set_property PACKAGE_PIN T14 [get_ports {g_in[7]}]
set_property PACKAGE_PIN T15 [get_ports {g_in[6]}]
set_property PACKAGE_PIN R13 [get_ports {g_in[5]}]
set_property PACKAGE_PIN T13 [get_ports {g_in[4]}]
set_property PACKAGE_PIN R15 [get_ports {g_in[3]}]
set_property PACKAGE_PIN R16 [get_ports {g_in[2]}]
set_property PACKAGE_PIN P13 [get_ports {g_in[1]}]
set_property PACKAGE_PIN P15 [get_ports {g_in[0]}]
set_property PACKAGE_PIN H5 [get_ports {r_in[7]}]
set_property PACKAGE_PIN H4 [get_ports {r_in[6]}]
set_property PACKAGE_PIN G1 [get_ports {r_in[5]}]
set_property PACKAGE_PIN T10 [get_ports {r_in[4]}]
set_property PACKAGE_PIN T9 [get_ports {r_in[3]}]
set_property PACKAGE_PIN P11 [get_ports {r_in[2]}]
set_property PACKAGE_PIN R12 [get_ports {r_in[1]}]
set_property PACKAGE_PIN T12 [get_ports {r_in[0]}]
set_property PACKAGE_PIN N11 [get_ports clk_27m]
set_property PACKAGE_PIN M14 [get_ports de_in]
set_property PACKAGE_PIN K15 [get_ports hs_in]
set_property PACKAGE_PIN K13 [get_ports i2c_data]
set_property PACKAGE_PIN P9 [get_ports it6802_rstn]
set_property PACKAGE_PIN K16 [get_ports vs_in]
set_property PACKAGE_PIN N13 [get_ports pclk]
set_property PACKAGE_PIN H3 [get_ports i2s_mclk]
set_property PACKAGE_PIN J3 [get_ports i2s_sck]
set_property PACKAGE_PIN J1 [get_ports i2s_sdin]
set_property PACKAGE_PIN K1 [get_ports i2s_ws]
set_property PACKAGE_PIN K12 [get_ports KEY]

set_property PACKAGE_PIN A7 [get_ports dip[0]]
set_property PACKAGE_PIN B7 [get_ports dip[1]]
set_property PACKAGE_PIN C7 [get_ports dip[2]]
set_property PACKAGE_PIN C6 [get_ports dip[3]]
set_property PACKAGE_PIN D5 [get_ports dip[4]]
set_property PACKAGE_PIN D6 [get_ports dip[5]]
set_property PACKAGE_PIN D4 [get_ports dip[6]]
set_property PACKAGE_PIN C4 [get_ports dip[7]]

set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_N]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_N]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_N]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_N]

set_property PACKAGE_PIN F4 [get_ports HDMI_D2_P]
set_property PACKAGE_PIN F2 [get_ports HDMI_D1_P]
set_property PACKAGE_PIN F5 [get_ports HDMI_CLK_P]
set_property PACKAGE_PIN G5 [get_ports HDMI_D0_P]

create_clock -period 6.667 -name pclk -waveform {0.000 3.333} [get_ports pclk]

#一下设置加速FLASH加载速度，后面代码请复制此处重新编译
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_MODE SPIx1 [current_design]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_27m_bufg]

