set_property SRC_FILE_INFO {cfile:E:/kehu/tianjingdaxue/UART/UART.srcs/constrs_1/new/Artix_pin.xdc rfile:../../../UART.srcs/constrs_1/new/Artix_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports clk_i]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports uart_rx_i]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports uart_tx_o]
